name: Android Build (Safe Gradle Installer)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Gradle if missing
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: 8.6

    - name: Grant execute permission for gradlew (ignore if missing)
      run: |
        if [ -f gradlew ]; then chmod +x gradlew; fi

    - name: Build APK safely
      run: |
        if [ -f gradlew ]; then
          ./gradlew assembleDebug --stacktrace
        else
          gradle assembleDebug --stacktrace
        fi

    - name: Upload generated APK
      uses: actions/upload-artifact@v4
      with:
        name: mishu_musicplayer-apk
        path: app/build/outputs/apk/debug/*.apk
